### ISSUE TITLE
why!

### ISSUE THREAD

**Issue by qwe3213** [qwe3213/BAEKJOON#2]
### 1번째
```javascript
let input = require('fs').readFileSync('inp.txt').toString().split('\n');

let a=input[0].split(' ').map(x => Number(x));

let count=0;
for(let i=0; i<a[0]; i++){
    if(a[0]+a[1]*i>=a[2]*i &&a[1]<a[2]){
        count++
   
    }else if(a[1]>=a[2]){
        count=-1
    }
}
console.log(count);
```

입력값을 1000 70 170 넣으면 
1000+ 770 >=  1870   이렇게되어서 11이나오는데
입력값  2100000000 9 10 넣으면 위의식대로면 
2100000000+9*2100000000 하면 
 21000000009이나와서 >=21000000010 하면
이렇게해서 2100000001이 나와야되는거같은데 1이부족하게나옴 2100000000 이나옴.

### 2번째
```javascript
let input = require('fs').readFileSync('inp.txt').toString().split(' ');

 

 const A=input[0] *1;  // 여기왜 *1하는지모르겠습니다..
 const B=input[1] *1; // 여기왜 *1하는지모르겠습니다.
 const C=input[2] *1; // 여기왜 *1하는지모르겠습니다.

 const margin =C-B;  
 const count=Math.floor(A/margin)+1 //위에서C-B의값을정하고 밑에서 계산하는데 편하게할려고 미리계산하는가싶어서 저는 그냥 바로 A/(C-B) 를했는데 틀렸습니다 왜다른건지...?
 console.log(C<=B ? -1 : count);
```

### 3번째
```javascript
let fs = require('fs');
// let input = fs.readFileSync('/dev/stdin').toString().split(' ');
 let input = fs.readFileSync ('inp.txt').toString().trim();
let X = Number(input)
let Counter =0;
const O =[];
const N =[];
while (X>0){
  Counter++;
  X=X-Counter
}  //여기서 X 가11일경우 X는 -4 Counter 는5가나오는데 이해가안됩니다 .ㅠㅠㅠ왜지?..

for(let i=0; i<Counter; i++){
    O.push(i+1);
    N.push(Counter-i);
    
} 
// if(Counter%2===0){
//     console.log(`${O[0]}/${N[0]}`);
// } else{
//     console.log(`${N[0]}/${O[0]}`);
// }

if(Counter%2===0){
    console.log(`${O[X+Counter-1]}/${N[X+Counter-1]}`);
}else {
    console.log(`${N[X+Counter-1]}/${O[X+Counter-1]}`)
} // 그리고 여기서 3이될경우 X는 0 Counter 는 2가되는데 그렇게되면
// N[1]/O[1]이되는데 위에보면 N[0]값만있는게아닌가? N[1]/O[1]이 왜답이되는지 모르겠습니다.
```

**Comment by gusah009** [comment]
일단 보기 좋게 수정을 좀 했습니다!

어떤 문제인지 기재가 안되어 있어서 모른 채로 답변 드리겠습니다. 다음엔 문제도 올려 주시면 감사하겠습니다!

### 1번째
`for(let i=0; i<a[0]; i++)` 여기에 답이 있습니다. `i`는 `a[0]`보다 작을 때만 `for`루프를 돌도록 되어 있는데, 말씀 하신 i가 **2,100,000,000**이 되는 순간 `for`루프를 나가기 때문에 **2,100,000,001**에 도달하지 못하게 되는 것입니다.

**Comment by gusah009** [comment]
### 2번째
#### 2-1) `input[0] * 1` 문제
`javascript`의 묵시적 형변환 때문입니다. 

[JavaScript의 형변환](https://www.secmem.org/blog/2020/03/19/javascript-type-coercion/)

위 자료를 참고하시면 될 것 같습니다. 나중에 왜 그런지 알게 되면 comment로 달아주세요~

#### 2-2)
```javascript
const margin =C-B;  
const count=Math.floor(A/margin)+1
```
`A / margin`과 `A / (C - B)`는 완벽하게 동일합니다. 틀릴 수가 없는데, 수정하신 코드도 보여주세요.

**Comment by gusah009** [comment]
### 3번째
#### 3-1)
```javascript
while (X>0) {
  Counter++;
  X=X-Counter
}  // 여기서 X 가11일경우 X는 -4 Counter 는5가나오는데 이해가안됩니다 .ㅠㅠㅠ왜지?..
```
이 부분은 직접 디버깅을 해보시면서 이해하는 것이 좋을 것 같습니다. 아래 코드를 돌려서 이해해봅시다!
```javascript
function func2(X) {
    let Counter =0;
    while (X>0){
        Counter++;
        X = X - Counter;
        console.log("Counter: " + Counter);
        console.log("X: " + X);
        console.log();
    }
}

func2(11); // 11이 곧 X값입니다. 여기 아무 값이나 넣어가면서 테스트해보세요!
```

#### 3-2)
```javascript
if(Counter%2===0){
    console.log(`${O[X+Counter-1]}/${N[X+Counter-1]}`);
}else {
    console.log(`${N[X+Counter-1]}/${O[X+Counter-1]}`)
} // 그리고 여기서 3이될경우 X는 0 Counter 는 2가되는데 그렇게되면
// N[1]/O[1]이되는데 위에보면 N[0]값만있는게아닌가? N[1]/O[1]이 왜답이되는지 모르겠습니다.
```
_여기서 3이될경우_ 라는 말이 무슨말인지 잘 모르겠지만, `Counter` 값이 2라면 첫 번째 if문인 `if(Counter%2 === 0)` 조건에 부합해서 `O[1]/N[1]` 이 출력됩니다.

**Comment by qwe3213** [comment]
수정해주셔서 감사합니다.  
1번째 문제는 덕분에 궁금증이 해결되었습니다. 
 2-1 문제같은경우는 문자형식인걸 숫자형식으로 바꿔주려고한거인가요?.. 
2-2는 다시해보니 잘작동이되네요  죄송합니다. ㅜㅜ
3-1 for문만써써 while문을 잘몰랐는데 잘 정리해주셔서 이해가 금방갔습니다.   감사합니다 ㅎㅎ
3-2 같은경우는 제가 질문을 잘못한거 같아서 다시정리하다 이해가 되었습니다.
while (X>0){
  Counter++;
  X=X-Counter
}
여기서 X는 3일시 X=0, Counter=2가 나옵니다.
그래서
for(let i=0; i<Counter; i++){
    O.push(i+1);
    N.push(Counter-i);  
} 
여기서 X는 0이고 Counter 의 값이 2일시 O의 값은 [ 1, 2 ]  N의 값은 [ 2, 1 ]가 나오게되어 O[1]/N[1] 의출력값은 2/1이 나오는것을 알게되었습니다.

다음엔 문제를 같이 기재해서 질문드리겠습니다 죄송하고 감사합니다!

**Comment by gusah009** [comment]
**2-1)** 같은 경우는 말씀하신대로 숫자 형식으로 바꿔주려는 의도로 작성한 코드인 것 같습니다.

여담으로, 코드 올릴 때 아래와 같이 하면 이쁘게 하이라이팅 되어서 올라갑니다!

**작성한 코드)**
````abap
```javascript
while (X>0){
  Counter++;
  X=X-Counter
}
```
````
**결과**
```javascript
while (X>0){
  Counter++;
  X=X-Counter
}
```

**Comment by qwe3213** [comment]
유익한 정보 감사합니다.  덕분에 많이 배웠습니다!!!!

**Comment by qwe3213** [comment]
백준문제 10250번 문제를 풀어봤는데
 ```let input = require('fs').readFileSync('inp.txt').toString().split('\n');
 let arr= 0;
 let answer =0;
 for(let i=1; i<=input[0]; i++){
  arr= input[i].split(' ')
  for(let j=0; j<=input[0]+1; j++){
   answer= `${arr[2]%arr[0]}`+`${Math.ceil(arr[2]/arr[0])}`
  }if(Math.ceil(arr[2]/arr[0])>=10){
    console.log(Number(answer));
  }else{
    answer= `${arr[2]%arr[0]}`+'0'+`${Math.ceil(arr[2]/arr[0])}`
    console.log(Number(answer));
  }
} ``` 
맨처음 숫자열로바꾸지않고내서 틀려서 다시 숫자열로 바꾸고 답을냈는데 출력값은  맞게 나오는데 왜틀렸는지 잘모르겠습니다.. ㅠㅠ

**Comment by gusah009** [comment]
> 백준문제 10250번 문제를 풀어봤는데
> 
> ```
> let arr= 0;
> let answer =0;
> for(let i=1; i<=input[0]; i++){
>  arr= input[i].split(' ')
>  for(let j=0; j<=input[0]+1; j++){
>   answer= `${arr[2]%arr[0]}`+`${Math.ceil(arr[2]/arr[0])}`
>  }if(Math.ceil(arr[2]/arr[0])>=10){
>    console.log(Number(answer));
>  }else{
>    answer= `${arr[2]%arr[0]}`+'0'+`${Math.ceil(arr[2]/arr[0])}`
>    console.log(Number(answer));
>  }
> } ``` 
> 맨처음 숫자열로바꾸지않고내서 틀려서 다시 숫자열로 바꾸고 답을냈는데 출력값은  맞게 나오는데 왜틀렸는지 잘모르겠습니다.. ㅠㅠ
> ```

이슈 새로 만들어서 올려주세요
그리고 code block이 `javascript`로 highlighting되게 만들어서 올려주시면 감사하겠습니다.
추가로 **백준 문제는 링크도 같이** 올려주세요.
- _Ex) [백준 문제 10250번](https://www.acmicpc.net/problem/10250)을 풀어봤는데 ..._
