### ISSUE TITLE
어디서 틀렸는지를 모르겠습니다..

### ISSUE THREAD

**Issue by qwe3213** [qwe3213/BAEKJOON#4]
```javascript
let fs = require("fs");
// let input = fs.readFileSync('/dev/stdin').toString().split(' ');
let input = fs.readFileSync("inp.txt").toString().split(" ");
let num = input.map((e) => Number(e));

for (let i = 1; i <= Math.ceil(num[0] / 3); i++) {
  if (num[0] % 5 == 0) {
    console.log(num[0] / 5);
    break;
  } else if ((num[0] - 3 * i) % 5 === 0) {
    console.log((num[0] - 3 * i) / 5 + i);
    break;
  } else if (
    (num[0] - 3 * i) % 5 !== 0 &&
    num[0] % 3 !== 0 &&
    num[0] % 5 !== 0
  ) {
    console.log(-1);
    break;
  }
}

```
1.저는 위의 코드처럼 입력값에서 5를나누고 나머지가 0일경우 가 제일 설탕을 적게 들고가는 방법이기에 먼저 썼습니다.
2. 그다음은 입력값에 3을빼고 5를나눠 나머지가 0이될경우가 2번째로 제일 적게 들고가는 방법이라생각하고 3번째가 3을나눴을때 0일경우 제일 많이들고가는 방법이라생각하여 위의 코드처럼 작성을 해보았습니다. 
3.그리고 그모든것이 되지않을경우는 -1로 만들었습니다.
 
그래서 입력 출력해보면 답이 잘 나왔으나  답이틀렸다고 나와서 제가 잘못작성한건지 아니면 중요한 요점을 놓친건지 잘모르겠어서 여쭤봅니다...ㅠㅠ

링크 :https://www.acmicpc.net/problem/2839
백준문제 2839번입니다.

**Comment by gusah009** [comment]
우선 issue를 깔끔하게 써 주셔서 감사합니다! 👍👍

반례입니다.
```
입력) 4999

코드 결과) -1
실제 정답) 1001
```

**Comment by qwe3213** [comment]
감사합니다 계속 고민해보니 for문으로 풀수있는 문제가 아닌거 같아 while문을 사용하여 다시 풀어 보았습니다.
```javascript
let fs = require('fs');
let input = fs.readFileSync('/dev/stdin').toString();

let N = Number(input);
let f = 0;
let t = 0;

while(true){
    if(N % 5 === 0){
        f = N / 5;
        console.log(f + t);
        break;
    }
    if(N < 0){
        console.log(-1);
        break;
    }
    N = N - 3;
    t++;
}
```
1. for문에서 했던거와 같이 우선 제일적은 설탕의 개수를 들때인 5의 나머지가 0일경우를 구한값을 구했습니다.
2. 그리고 맨밑에서 N에서 3을계속빼주고 5를나눠주는데 나오지않아서 N이 0보다 작아질때를 -1로 값을 정했습니다.
3.  2번에서 말했다싶이 맨밑에서  3을 한번식 계속 뺴주는 식으로 정했습니다.
덕분에 어디가 문제이고 다른방법을 찾을수 있었습니다. 감사합니다!!!!
